### ISSUE TITLE
Firmata install

### ISSUE THREAD

**Issue by ymollard** [arbalet-project/ArbaletMeki#1]
https://github.com/arbalet-project/ArbaletMeki/blob/master/documentation/USERDOC.md#L34-L34
I got an exception with this firmware:
```
UnhandledPromiseRejectionWarning: IncorrectFirmataVersionError: Please upload NodePixel Firmata to the board
```

The commands below install the nodePixel firmware that actually works; Is there an error in the user doc?
```
npm install -g nodebots-interchange
interchange install git+https://github.com/ajfisher/node-pixel -a uno --firmata
```

**Comment by lucdems** [comment]
Yes that's an error.

I put the wrong firmware in the doc, the Standard Firmata firmware was used in the earlier versions of development. I totally forgot that I had to install a special custom firmata firmware for node-pixel that is required to work with the WS2812b led strip.

I correct the user doc as soon as possible.
